const mongoose = require('mongoose');
require('dotenv').config();

const Puzzle = require('./models/Puzzle');
const EngagementContent = require('./models/EngagementContent');

const puzzles = [
    // KIDS (Under 15)
    { question: "Find the odd one out: 🍎, 🍌, ✈️, 🍉", answer: "✈️", options: ["🍎", "🍌", "✈️", "🍉"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "What is 2 + 3?", answer: "5", options: ["4", "5", "6", "7"], category: "math", difficulty: "easy", ageGroup: "kids" },
    { question: "What comes next? 2, 4, 6, 8, ?", answer: "10", options: ["9", "10", "11", "12"], category: "math", difficulty: "medium", ageGroup: "kids" },
    { question: "Guess the animal: 🐶 + 🏠", answer: "Dog", options: ["Cat", "Dog", "Bird", "Fish"], category: "emoji", difficulty: "easy", ageGroup: "kids" },
    { question: "Complete the pattern: Red, Blue, Red, Blue, ?", answer: "Red", options: ["Green", "Yellow", "Red", "Blue"], category: "pattern", difficulty: "easy", ageGroup: "kids" },
    { question: "Which word starts with 'B'? Apple, Banana, Cherry", answer: "Banana", options: ["Apple", "Banana", "Cherry", "Date"], category: "word", difficulty: "easy", ageGroup: "kids" },
    { question: "Guess the word: 🌧️ + 🏹", answer: "Rainbow", options: ["Raindrop", "Bowtie", "Rainbow", "Weather"], category: "emoji", difficulty: "medium", ageGroup: "kids" },
    { question: "If you have 3 apples and you eat 1, how many are left?", answer: "2", options: ["1", "2", "3", "4"], category: "logic", difficulty: "medium", ageGroup: "kids" },
    { question: "Unscramble: A E P L P", answer: "Apple", options: ["Paper", "Apple", "Lapel", "Pale"], category: "word", difficulty: "medium", ageGroup: "kids" },
    { question: "What has legs but cannot walk?", answer: "Table", options: ["Snake", "Table", "Car", "River"], category: "logic", difficulty: "hard", ageGroup: "kids" },
    { question: "10 - ? = 4", answer: "6", options: ["5", "6", "7", "8"], category: "math", difficulty: "hard", ageGroup: "kids" },
    { question: "Which shape has 3 sides?", answer: "Triangle", options: ["Square", "Circle", "Triangle", "Star"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "0, 5, 10, 15, ?", answer: "20", options: ["16", "18", "20", "25"], category: "pattern", difficulty: "medium", ageGroup: "kids" },
    { question: "What is the capital of France?", answer: "Paris", options: ["London", "Berlin", "Paris", "Rome"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "If you freeze water, what do you get?", answer: "Ice", options: ["Ice", "Steam", "Rain", "Snow"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "What is 5 x 2?", answer: "10", options: ["7", "8", "9", "10"], category: "math", difficulty: "easy", ageGroup: "kids" },
    { question: "Which planet is known as the Red Planet?", answer: "Mars", options: ["Venus", "Mars", "Jupiter", "Saturn"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "How many legs does a spider have?", answer: "8", options: ["4", "6", "8", "10"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "What has keys but can't open locks?", answer: "A piano", options: ["A piano", "A map", "A tree", "A car"], category: "logic", difficulty: "medium", ageGroup: "kids" },
    { question: "What color are emeralds?", answer: "Green", options: ["Blue", "Red", "Green", "Yellow"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "Which is the largest mammal in the world?", answer: "Blue Whale", options: ["Elephant", "Blue Whale", "Giraffe", "Shark"], category: "logic", difficulty: "medium", ageGroup: "kids" },
    { question: "What do bees make?", answer: "Honey", options: ["Milk", "Honey", "Sugar", "Wax"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "How many colors are in a rainbow?", answer: "7", options: ["5", "6", "7", "8"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "Riddle: I have a tail and a head, but no body. What am I?", answer: "A coin", options: ["A snake", "A coin", "A dog", "A comet"], category: "logic", difficulty: "medium", ageGroup: "kids" },
    { question: "Riddle: What has to be broken before you can use it?", answer: "An egg", options: ["A box", "An egg", "A lock", "A promise"], category: "logic", difficulty: "easy", ageGroup: "kids" },
    { question: "Riddle: What is full of holes but still holds water?", answer: "A sponge", options: ["A bucket", "A net", "A sponge", "A sieve"], category: "logic", difficulty: "medium", ageGroup: "kids" },
    { question: "Riddle: What gets wetter as it dries?", answer: "A towel", options: ["A sponge", "A towel", "A cloud", "Rain"], category: "logic", difficulty: "medium", ageGroup: "kids" },
    { question: "Riddle: I’m tall when I’m young, and I’m short when I’m old. What am I?", answer: "A candle", options: ["A tree", "A candle", "A pencil", "A building"], category: "logic", difficulty: "hard", ageGroup: "kids" },
    { question: "Riddle: What month of the year has 28 days?", answer: "All of them", options: ["February", "January", "June", "All of them"], category: "logic", difficulty: "medium", ageGroup: "kids" },
    { question: "Riddle: David’s parents have three sons: Snap, Crackle, and what’s the name of the third?", answer: "David", options: ["Pop", "John", "David", "Mike"], category: "logic", difficulty: "hard", ageGroup: "kids" },

    // TEENAGERS (15–20)
    { question: "Identify the movie: 🕷️ + 👨", answer: "Spider-Man", options: ["Ant-Man", "Batman", "Spider-Man", "Iron Man"], category: "emoji", difficulty: "easy", ageGroup: "teens" },
    { question: "What is 15 - 8?", answer: "7", options: ["6", "7", "8", "9"], category: "math", difficulty: "easy", ageGroup: "teens" },
    { question: "Fill in the blank: T _ M E", answer: "I", options: ["A", "E", "I", "O"], category: "word", difficulty: "easy", ageGroup: "teens" },
    { question: "Next in sequence: 1, 3, 5, 7, ?", answer: "9", options: ["8", "9", "10", "11"], category: "pattern", difficulty: "easy", ageGroup: "teens" },
    { question: "Solve: 5 x 6 = ?", answer: "30", options: ["25", "30", "35", "40"], category: "math", difficulty: "medium", ageGroup: "teens" },
    { question: "Which emoji doesn't belong? ⚽ 🏀 🍎 🏐", answer: "🍎", options: ["⚽", "🏀", "🍎", "🏐"], category: "spot-difference", difficulty: "medium", ageGroup: "teens" },
    { question: "I speak without a mouth and hear without ears. What am I?", answer: "Echo", options: ["Wind", "Echo", "Shadow", "Ghost"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "Unscramble: O M C P U T R E", answer: "Computer", options: ["Commuter", "Computer", "Compare", "Compute"], category: "word", difficulty: "medium", ageGroup: "teens" },
    { question: "If 3 cats catch 3 mice in 3 minutes, how many cats catch 100 mice in 100 minutes?", answer: "3", options: ["100", "3", "33", "10"], category: "logic", difficulty: "hard", ageGroup: "teens" },
    { question: "What is the square root of 144?", answer: "12", options: ["10", "11", "12", "14"], category: "math", difficulty: "hard", ageGroup: "teens" },
    { question: "Next in pattern: J, F, M, A, M, J, ?", answer: "J", options: ["A", "S", "O", "J"], category: "pattern", difficulty: "hard", ageGroup: "teens" },
    { question: "A girl has as many brothers as sisters, but each boy has only half as many brothers as sisters. How many brothers and sisters are there?", answer: "4 sisters, 3 brothers", options: ["3 sisters, 2 brothers", "4 sisters, 3 brothers", "5 sisters, 4 brothers", "2 sisters, 1 brother"], category: "logic", difficulty: "hard", ageGroup: "teens" },
    { question: "What is the chemical symbol for gold?", answer: "Au", options: ["Ag", "Au", "Pb", "Fe"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci", options: ["Pablo Picasso", "Vincent van Gogh", "Leonardo da Vinci", "Claude Monet"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "Identify the movie: 🦁 + 👑", answer: "The Lion King", options: ["Madagascar", "The Lion King", "Jungle Book", "Dumbo"], category: "emoji", difficulty: "easy", ageGroup: "teens" },
    { question: "What is 12 x 12?", answer: "144", options: ["124", "134", "144", "154"], category: "math", difficulty: "medium", ageGroup: "teens" },
    { question: "If the day before yesterday was Thursday, what day will it be the day after tomorrow?", answer: "Monday", options: ["Sunday", "Monday", "Tuesday", "Wednesday"], category: "logic", difficulty: "hard", ageGroup: "teens" },
    { question: "Which gas do plants absorb from the atmosphere?", answer: "Carbon dioxide", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "What is the largest organ in the human body?", answer: "Skin", options: ["Liver", "Heart", "Skin", "Lungs"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "Riddle: What has an eye but cannot see?", answer: "A needle", options: ["A needle", "A cyclops", "A storm", "A potato"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "Riddle: What goes up but never comes back down?", answer: "Your age", options: ["A balloon", "Your age", "A rocket", "Smoke"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "Riddle: The more of this there is, the less you see. What is it?", answer: "Darkness", options: ["Light", "Fog", "Darkness", "Rain"], category: "logic", difficulty: "hard", ageGroup: "teens" },
    { question: "Riddle: I have many keys but can’t open a single lock. What am I?", answer: "A piano", options: ["A keyboard", "A piano", "A safe", "A map"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "Riddle: What belongs to you, but other people use it more than you?", answer: "Your name", options: ["Your phone", "Your name", "Your car", "Your house"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "Riddle: What can you catch but not throw?", answer: "A cold", options: ["A ball", "A cold", "A joke", "A breath"], category: "logic", difficulty: "medium", ageGroup: "teens" },
    { question: "Riddle: What has cities, but no houses; forests, but no trees; and water, but no fish?", answer: "A map", options: ["A painting", "A map", "A globe", "A dream"], category: "logic", difficulty: "hard", ageGroup: "teens" },
    { question: "Riddle: What is so fragile that saying its name breaks it?", answer: "Silence", options: ["Glass", "Silence", "Ice", "A promise"], category: "logic", difficulty: "hard", ageGroup: "teens" },
    { question: "Solve for x: 3x + 5 = 20", answer: "5", options: ["3", "4", "5", "6"], category: "math", difficulty: "hard", ageGroup: "teens" },
    { question: "Which element has the atomic number 1?", answer: "Hydrogen", options: ["Helium", "Oxygen", "Hydrogen", "Carbon"], category: "logic", difficulty: "hard", ageGroup: "teens" },
    { question: "What is the speed of light?", answer: "299,792 km/s", options: ["150,000 km/s", "299,792 km/s", "450,000 km/s", "1,000,000 km/s"], category: "logic", difficulty: "hard", ageGroup: "teens" },
    // TEENAGERS — Bollywood Comedy Movies (Emoji Guess)
    { question: "🏃💨🏃💨 — This Bollywood comedy has two men running away from trouble across India. Name it!", answer: "Bhagam Bhaag", options: ["Dhamaal", "Bhagam Bhaag", "Housefull", "Golmaal"], category: "emoji", difficulty: "medium", ageGroup: "teens" },
    { question: "🏠🎉🎊🛏️ — A chaotic comedy set in a hotel with mix-ups, fights and laughter! Name this Bollywood hit.", answer: "Housefull", options: ["Housefull", "Grand Masti", "Welcome", "Phir Hera Pheri"], category: "emoji", difficulty: "medium", ageGroup: "teens" },
    { question: "⛵🌊😂🎯 — Three bumbling friends find a mysterious bag on a beach and chaos follows. Which Bollywood comedy is this?", answer: "Dhamaal", options: ["Dhamaal", "No Entry", "Golmaal", "Chup Chup Ke"], category: "emoji", difficulty: "medium", ageGroup: "teens" },
    { question: "👨‍👨‍👦🏍️💼😂 — A Bollywood comedy about friends getting into money trouble because of a deal gone wrong. Name it!", answer: "Phir Hera Pheri", options: ["Hera Pheri", "Phir Hera Pheri", "Partner", "Mujhse Shaadi Karogi"], category: "emoji", difficulty: "hard", ageGroup: "teens" },
    { question: "🎭🏡👻😂 — A Bollywood horror-comedy about a haunted house and a confused family. What's the movie?", answer: "Bhool Bhulaiyaa", options: ["Bhool Bhulaiyaa", "Golmaal Returns", "Aankhen", "Judwaa"], category: "emoji", difficulty: "medium", ageGroup: "teens" },
    // TEENAGERS — Hollywood Marvel & Disney Movies (Emoji Guess)
    { question: "🕷️🏙️🎒🏫 — A young superhero balances school and saving the city with web-slinging powers. Which Marvel movie?", answer: "Spider-Man: Homecoming", options: ["Spider-Man Homecoming", "Doctor Strange", "Ant-Man", "Black Panther"], category: "emoji", difficulty: "medium", ageGroup: "teens" },
    { question: "🧊❄️👯‍♀️💜 — Two royal sisters, one with ice powers, one on a quest to save her kingdom. Which Disney movie?", answer: "Frozen", options: ["Moana", "Frozen", "Tangled", "Brave"], category: "emoji", difficulty: "easy", ageGroup: "teens" },
    { question: "🦾🤖❤️🦸 — A billionaire builds an iron suit to become a superhero. Which Marvel movie is this?", answer: "Iron Man", options: ["Iron Man", "Thor", "Captain America", "The Hulk"], category: "emoji", difficulty: "easy", ageGroup: "teens" },
    { question: "🐟🌊🔍👀 — A forgetful fish helps find a lost clownfish's son. Which Disney Pixar film?", answer: "Finding Dory", options: ["Finding Nemo", "Finding Dory", "The Little Mermaid", "Shark Tale"], category: "emoji", difficulty: "medium", ageGroup: "teens" },
    { question: "⚡🔨👑🌈🌉 — A mighty Norse god is sent to Earth and must prove worthy to reclaim his hammer. Which Marvel movie?", answer: "Thor", options: ["Thor", "Avengers", "Captain America", "Doctor Strange"], category: "emoji", difficulty: "easy", ageGroup: "teens" },
    { question: "Identify the brand: 🍎 + 💻", answer: "Apple", options: ["Microsoft", "Apple", "Dell", "HP"], category: "emoji", difficulty: "easy", ageGroup: "adults" },
    { question: "Solve: 12 + 15", answer: "27", options: ["25", "26", "27", "28"], category: "math", difficulty: "easy", ageGroup: "adults" },
    { question: "Spot the difference: 🚘 🚗 🚘 🚘", answer: "🚗", options: ["🚘 (1)", "🚗", "🚘 (3)", "🚘 (4)"], category: "spot-difference", difficulty: "easy", ageGroup: "adults" },
    { question: "Next in pattern: 2, 4, 8, 16, ?", answer: "32", options: ["24", "30", "32", "64"], category: "pattern", difficulty: "easy", ageGroup: "adults" },
    { question: "What goes up but never comes down?", answer: "Age", options: ["Balloon", "Smoke", "Age", "Bird"], category: "logic", difficulty: "medium", ageGroup: "adults" },
    { question: "Unscramble: I R N O N E M E T V N", answer: "Environment", options: ["Enlightenment", "Environment", "Entertainment", "Improvement"], category: "word", difficulty: "medium", ageGroup: "adults" },
    { question: "Solve: 8 x 7 + 4", answer: "60", options: ["56", "60", "64", "68"], category: "math", difficulty: "medium", ageGroup: "adults" },
    { question: "What gets wetter the more it dries?", answer: "Towel", options: ["Sponge", "Towel", "Water", "Air"], category: "logic", difficulty: "medium", ageGroup: "adults" },
    { question: "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?", answer: "$0.05", options: ["$0.10", "$0.05", "$0.01", "$1.00"], category: "math", difficulty: "hard", ageGroup: "adults" },
    { question: "Next in pattern: 1, 1, 2, 3, 5, 8, ?", answer: "13", options: ["10", "11", "12", "13"], category: "pattern", difficulty: "hard", ageGroup: "adults" },
    { question: "I have branches, but no fruit, trunk or leaves. What am I?", answer: "Bank", options: ["River", "Bank", "Tree", "Company"], category: "logic", difficulty: "hard", ageGroup: "adults" },
    { question: "If 1=3, 2=3, 3=5, 4=4, 5=4, then 6=?", answer: "3", options: ["3", "4", "5", "6"], category: "pattern", difficulty: "hard", ageGroup: "adults" },
    { question: "What is the capital of Japan?", answer: "Tokyo", options: ["Seoul", "Beijing", "Tokyo", "Bangkok"], category: "logic", difficulty: "easy", ageGroup: "adults" },
    { question: "Which is the longest river in the world?", answer: "Nile", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], category: "logic", difficulty: "medium", ageGroup: "adults" },
    { question: "How many continents are there?", answer: "7", options: ["5", "6", "7", "8"], category: "logic", difficulty: "easy", ageGroup: "adults" },
    { question: "What is the value of Pi (to 2 decimal places)?", answer: "3.14", options: ["3.12", "3.14", "3.16", "3.18"], category: "math", difficulty: "medium", ageGroup: "adults" },
    { question: "Identify the movie: 🚢 + 🧊 + 💔", answer: "Titanic", options: ["Ice Age", "Titanic", "Love Story", "Jaws"], category: "emoji", difficulty: "easy", ageGroup: "adults" },
    { question: "Riddle: I have keys but no doors. I have space but no rooms. You can enter but you can’t go outside. What am I?", answer: "A keyboard", options: ["A house", "A keyboard", "A computer", "A mind"], category: "logic", difficulty: "hard", ageGroup: "adults" },
    { question: "Riddle: What runs all around a backyard, yet never moves?", answer: "A fence", options: ["A dog", "A fence", "A path", "A house"], category: "logic", difficulty: "hard", ageGroup: "adults" },
    { question: "Riddle: What can you keep after giving it to someone else?", answer: "Your word", options: ["Money", "Your word", "A gift", "Advice"], category: "logic", difficulty: "hard", ageGroup: "adults" },
    { question: "Riddle: I shaving every day, but my beard stays the same. What am I?", answer: "A barber", options: ["A man", "A barber", "A grandfather", "A teenager"], category: "logic", difficulty: "medium", ageGroup: "adults" },
    { question: "Riddle: Where does today come before yesterday?", answer: "The dictionary", options: ["A calendar", "The dictionary", "A time machine", "Space"], category: "logic", difficulty: "hard", ageGroup: "adults" },
    { question: "Riddle: What has a neck but no head?", answer: "A bottle", options: ["A bottle", "A shirt", "A drum", "A coat"], category: "logic", difficulty: "medium", ageGroup: "adults" },
    { question: "What is the pH level of pure water?", answer: "7", options: ["5", "6", "7", "8"], category: "logic", difficulty: "medium", ageGroup: "adults" },
    { question: "Which planet is the largest in our solar system?", answer: "Jupiter", options: ["Saturn", "Jupiter", "Neptune", "Uranus"], category: "logic", difficulty: "medium", ageGroup: "adults" },
    { question: "What is the chemical formula for table salt?", answer: "NaCl", options: ["H2O", "NaCl", "CO2", "O2"], category: "logic", difficulty: "medium", ageGroup: "adults" },
    { question: "Riddle: I am an odd number. Take away a letter and I become even. What number am I?", answer: "Seven", options: ["Three", "Five", "Seven", "Nine"], category: "logic", difficulty: "hard", ageGroup: "adults" },
    { question: "Who is known as the inventor of the telephone?", answer: "Alexander Graham Bell", options: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Albert Einstein"], category: "logic", difficulty: "medium", ageGroup: "adults" },
    { question: "What is the smallest prime number?", answer: "2", options: ["1", "2", "3", "5"], category: "math", difficulty: "medium", ageGroup: "adults" },
    { question: "Which year did World War II end?", answer: "1945", options: ["1918", "1939", "1945", "1950"], category: "logic", difficulty: "medium", ageGroup: "adults" },

    // ADULTS — Bollywood Comedy Movies (Emoji Guess)
    { question: "🏃💨🏃💨🚂🇮🇳 — A laugh riot with two men on the run across India, dodging trouble at every turn. Name this Bollywood comedy!", answer: "Bhagam Bhaag", options: ["Bhagam Bhaag", "Dhol", "No Entry", "Hulchul"], category: "emoji", difficulty: "medium", ageGroup: "adults" },
    { question: "🏠🔄😅💍👩‍❤️‍👨 — Multiple couples and mix-ups in one house packed with comedy chaos. Which Bollywood film?", answer: "Housefull 2", options: ["Housefull 2", "Dulha Mil Gaya", "Ready", "Full Masti"], category: "emoji", difficulty: "medium", ageGroup: "adults" },
    { question: "💸🤑😂🙏 — Three friends accidentally get a huge sum of money and their plan to return it creates endless comedy. Name it!", answer: "Hera Pheri", options: ["Hera Pheri", "Munna Bhai", "Welcome", "Chashme Baddoor"], category: "emoji", difficulty: "easy", ageGroup: "adults" },
    { question: "🎪😂👨‍👩‍👧‍👦🎭🇮🇳 — Raju, Babu and Shyam's misadventures inspired many memes & sequels. Which iconic comedy?", answer: "Andaz Apna Apna", options: ["Andaz Apna Apna", "Jo Jeeta Wohi Sikandar", "Rangeela", "Ram Lakhan"], category: "emoji", difficulty: "hard", ageGroup: "adults" },
    { question: "🚨😂👮‍♂️🕵️‍♂️🏃 — A bumbling cop chases the wrong criminals and gets tangled in a web of misunderstandings. Name this comedy!", answer: "Golmaal", options: ["Golmaal", "Singham", "Dabangg", "Rowdy Rathore"], category: "emoji", difficulty: "medium", ageGroup: "adults" },
    // ADULTS — Hollywood Marvel & Disney Movies (Emoji Guess)
    { question: "⚙️🐜🔬🦸 — A scientist shrinks down to ant-size using a special suit to save the world. Which Marvel movie?", answer: "Ant-Man", options: ["Ant-Man", "The Wasp", "Iron Fist", "Black Widow"], category: "emoji", difficulty: "medium", ageGroup: "adults" },
    { question: "🌌💥⚡🌀🧙 — A former surgeon becomes a master of the mystic arts to protect Earth from sorcery. Which Marvel film?", answer: "Doctor Strange", options: ["Doctor Strange", "Thor Ragnarok", "Eternals", "Moon Knight"], category: "emoji", difficulty: "medium", ageGroup: "adults" },
    { question: "🦁🐗🌴👑🌍 — An orphaned cub grows up outside his kingdom and must reclaim his royal throne. Which Disney classic?", answer: "The Lion King", options: ["The Lion King", "The Jungle Book", "Bambi", "Brother Bear"], category: "emoji", difficulty: "easy", ageGroup: "adults" },
    { question: "💎🌿🏔️🦅🌺 — An African king must defend his technologically advanced hidden kingdom. Which Marvel movie?", answer: "Black Panther", options: ["Black Panther", "Wakanda Forever", "Thor", "Captain Marvel"], category: "emoji", difficulty: "easy", ageGroup: "adults" },
    { question: "🌀🕸️♾️💥🦸‍♂️🦸‍♀️ — Every superhero teams up to reverse a cosmic villain's snap that wiped half of all life. Which Marvel epic?", answer: "Avengers: Endgame", options: ["Avengers Endgame", "Infinity War", "Civil War", "Age of Ultron"], category: "emoji", difficulty: "medium", ageGroup: "adults" },
    { question: "Solve: 50 + 25", answer: "75", options: ["65", "70", "75", "80"], category: "math", difficulty: "easy", ageGroup: "seniors" },
    { question: "Identify the phrase: ⏰ = 💰", answer: "Time is money", options: ["Time is gold", "Time flies", "Time is money", "Money buys time"], category: "emoji", difficulty: "easy", ageGroup: "seniors" },
    { question: "Next in pattern: 10, 20, 30, 40, ?", answer: "50", options: ["45", "50", "55", "60"], category: "pattern", difficulty: "easy", ageGroup: "seniors" },
    { question: "Which word starts with 'S'? Tree, Sun, Moon", answer: "Sun", options: ["Tree", "Sun", "Moon", "Star"], category: "word", difficulty: "easy", ageGroup: "seniors" },
    { question: "What has hands but can not clap?", answer: "Clock", options: ["Clock", "Tree", "Monkey", "Robot"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "Identify the movie: 🚢 + 🧊 + 💔", answer: "Titanic", options: ["Ice Age", "Titanic", "Love Story", "Jaws"], category: "emoji", difficulty: "medium", ageGroup: "seniors" },
    { question: "Solve for x: x + 15 = 40", answer: "25", options: ["20", "25", "30", "35"], category: "math", difficulty: "medium", ageGroup: "seniors" },
    { question: "Spot the difference: ☕ ☕ 🍵 ☕", answer: "🍵", options: ["☕ (1)", "☕ (2)", "🍵", "☕ (4)"], category: "spot-difference", difficulty: "medium", ageGroup: "seniors" },
    { question: "Unscramble: Y M M E O R", answer: "Memory", options: ["Mirror", "Memory", "Money", "Monkey"], category: "word", difficulty: "medium", ageGroup: "seniors" },
    { question: "Next in sequence: 2, 6, 12, 20, 30, ?", answer: "42", options: ["36", "40", "42", "48"], category: "pattern", difficulty: "hard", ageGroup: "seniors" },
    { question: "Mary's father has 5 daughters: 1. Nana, 2. Nene, 3. Nini, 4. Nono. What is the name of the 5th daughter?", answer: "Mary", options: ["Nunu", "Nina", "Mary", "None"], category: "logic", difficulty: "hard", ageGroup: "seniors" },
    { question: "Solve: 15% of 200", answer: "30", options: ["15", "20", "30", "40"], category: "math", difficulty: "hard", ageGroup: "seniors" },
    { question: "What begins with T, ends with T, and has T in it?", answer: "Teapot", options: ["Tent", "Tart", "Teapot", "Toast"], category: "logic", difficulty: "hard", ageGroup: "seniors" },
    { question: "Who was the first person to walk on the moon?", answer: "Neil Armstrong", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "What is the largest country in the world by area?", answer: "Russia", options: ["Canada", "China", "USA", "Russia"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "Which vitamin is produced when a person is exposed to sunlight?", answer: "Vitamin D", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "What is the capital of the United Kingdom?", answer: "London", options: ["London", "Dublin", "Edinburgh", "Cardiff"], category: "logic", difficulty: "easy", ageGroup: "seniors" },
    { question: "Which musical instrument has 88 keys?", answer: "Piano", options: ["Guitar", "Violin", "Piano", "Flute"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "Riddle: What has many rings but no fingers?", answer: "A telephone", options: ["A tree", "A telephone", "A circus", "Saturn"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "Riddle: I make a loud sound when changing, I grow larger but weigh less. What am I?", answer: "Popcorn", options: ["A balloon", "Popcorn", "A cloud", "Thunder"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "Riddle: What comes once in a minute, twice in a moment, but never in a thousand years?", answer: "The letter M", options: ["A blink", "The letter M", "A thought", "A second"], category: "logic", difficulty: "hard", ageGroup: "seniors" },
    { question: "Riddle: If you have me, you want to share me; if you share me, you haven't kept me. What am I?", answer: "A secret", options: ["A joke", "A secret", "Money", "A gift"], category: "logic", difficulty: "hard", ageGroup: "seniors" },
    { question: "Riddle: What has a thumb and four fingers but is not a hand?", answer: "A glove", options: ["A sock", "A glove", "A shoe", "A hat"], category: "logic", difficulty: "hard", ageGroup: "seniors" },
    { question: "Riddle: What has words, but never speaks?", answer: "A book", options: ["A book", "A radio", "A sign", "A teacher"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "Which year did the Berlin Wall fall?", answer: "1989", options: ["1987", "1989", "1991", "1993"], category: "logic", difficulty: "hard", ageGroup: "seniors" },
    { question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "What is the most common gas in the Earth's atmosphere?", answer: "Nitrogen", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"], category: "logic", difficulty: "hard", ageGroup: "seniors" },
    { question: "Who painted 'The Starry Night'?", answer: "Vincent van Gogh", options: ["Pablo Picasso", "Vincent van Gogh", "Leonardo da Vinci", "Claude Monet"], category: "logic", difficulty: "medium", ageGroup: "seniors" },
    { question: "What is the deepest ocean in the world?", answer: "Pacific Ocean", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], category: "logic", difficulty: "hard", ageGroup: "seniors" },
    { question: "Riddle: What can travel around the world while staying in a corner?", answer: "A stamp", options: ["A letter", "A stamp", "A bird", "A thought"], category: "logic", difficulty: "hard", ageGroup: "seniors" }
];

const contentItems = [
    // KIDS
    { type: "fact", content: "Did you know? Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!", ageGroup: "kids" },
    { type: "tip", content: "A healthy tip: Eating breakfast helps your brain wake up and stay focused for learning all day!", ageGroup: "kids" },
    { type: "poetry", content: "Twinkle, twinkle, little star, how I wonder what you are. Up above the world so high, like a diamond in the sky.", ageGroup: "kids" },
    { type: "reading", content: "Elephants are the largest land animals. They are very social and live in groups called herds. They can even recognize themselves in a mirror!", ageGroup: "kids" },
    { type: "fact", content: "A snail can sleep for three years.", ageGroup: "kids" },
    { type: "fact", content: "The heart of a shrimp is located in its head.", ageGroup: "kids" },
    { type: "tip", content: "Wash your hands for 20 seconds to keep the germs away!", ageGroup: "kids" },
    { type: "fact", content: "Octopuses have three hearts.", ageGroup: "kids" },
    { type: "reading", content: "The blue whale is so big that a human could swim through its arteries!", ageGroup: "kids" },
    { type: "fact", content: "Koalas have fingerprints, just like humans.", ageGroup: "kids" },
    { type: "fact", content: "Bananas are berries, but strawberries are not!", ageGroup: "kids" },
    { type: "fact", content: "A group of flamingos is called a flamboyance.", ageGroup: "kids" },
    { type: "tip", content: "Reading just 15 minutes every day can improve your imagination and vocabulary.", ageGroup: "kids" },
    { type: "reading", content: "The cheetah is the fastest land animal and can run up to 70 miles per hour for short distances.", ageGroup: "kids" },
    { type: "poetry", content: "Little drops of water, little grains of sand, make the mighty ocean and the pleasant land.", ageGroup: "kids" },
    { type: "fact", content: "Space is completely silent because there is no air to carry sound waves.", ageGroup: "kids" },
    { type: "fact", content: "The footprints on the Moon will be there for 100 million years because there is no wind to blow them away.", ageGroup: "kids" },
    { type: "fact", content: "A baby octopus is about the size of a flea when it is born.", ageGroup: "kids" },
    { type: "fact", content: "The Sun is a star and it is so big that 1.3 million Earths could fit inside it.", ageGroup: "kids" },
    { type: "fact", content: "Saturn has huge rings made of ice and dust.", ageGroup: "kids" },
    { type: "tip", content: "Drinking plenty of water makes your skin look great and helps your body work well.", ageGroup: "kids" },
    { type: "tip", content: "Always wear your helmet when riding a bike to protect your brain!", ageGroup: "kids" },
    { type: "tip", content: "Saying 'thank you' and 'please' makes people around you happy.", ageGroup: "kids" },
    { type: "reading", content: "Astronauts eat special food in space that doesn't make crumbs, because crumbs could float into their eyes or machines!", ageGroup: "kids" },
    { type: "reading", content: "Mars is called the Red Planet because its surface is covered in reddish iron oxide, similar to rust.", ageGroup: "kids" },
    { type: "fact", content: "Venus is the hottest planet in our solar system, even though Mercury is closer to the Sun.", ageGroup: "kids" },
    { type: "fact", content: "One day on Venus is longer than one year on Venus!", ageGroup: "kids" },
    { type: "fact", content: "Jupiter is the largest planet and has a 'Great Red Spot' which is actually a giant storm.", ageGroup: "kids" },
    { type: "tip", content: "Sharing your toys with friends makes playtime more fun for everyone.", ageGroup: "kids" },
    { type: "tip", content: "Try to eat a piece of fruit instead of candy when you want something sweet.", ageGroup: "kids" },

    // TEENS
    { type: "quote", content: "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt", ageGroup: "teens" },
    { type: "fact", content: "An average person spends about six months of their entire life waiting for red lights to turn green.", ageGroup: "teens" },
    { type: "tip", content: "Productivity hack: The Pomodoro Technique suggests working for 25 minutes and then taking a 5-minute break to stay fresh.", ageGroup: "teens" },
    { type: "reading", content: "In 1945, a group of Soviet school children presented a hand-carved US Seal to the US Ambassador. It contained a listening device that went undetected for seven years.", ageGroup: "teens" },
    { type: "fact", content: "Instagram was originally called Burbn.", ageGroup: "teens" },
    { type: "tip", content: "Learn one new word every day to expand your vocabulary effortlessly.", ageGroup: "teens" },
    { type: "quote", content: "It does not matter how slowly you go as long as you do not stop. — Confucius", ageGroup: "teens" },
    { type: "fact", content: "Turtles can breathe through their butts.", ageGroup: "teens" },
    { type: "reading", content: "The Great Wall of China is not visible from space with the naked eye, despite the popular myth.", ageGroup: "teens" },
    { type: "tip", content: "Backup your photos and files regularly to avoid losing them accidentally.", ageGroup: "teens" },
    { type: "quote", content: "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau", ageGroup: "teens" },
    { type: "fact", content: "Your brain generates enough electricity to power a small light bulb.", ageGroup: "teens" },
    { type: "tip", content: "Learning basic coding skills can open many career opportunities in the future.", ageGroup: "teens" },
    { type: "reading", content: "The internet sends millions of emails every second, connecting people across the globe instantly.", ageGroup: "teens" },
    { type: "fact", content: "The human brain processes images 60,000 times faster than text.", ageGroup: "teens" },
    { type: "fact", content: "A day on Mercury lasts about 59 Earth days, and a year lasts about 88 Earth days.", ageGroup: "teens" },
    { type: "fact", content: "Neutron stars are so dense that a teaspoon of their material would weigh 6 billion tons.", ageGroup: "teens" },
    { type: "fact", content: "The universe is estimated to be about 13.8 billion years old.", ageGroup: "teens" },
    { type: "fact", content: "Black holes are regions of space where gravity is so strong that even light cannot escape.", ageGroup: "teens" },
    { type: "fact", content: "There are more stars in the universe than grains of sand on all the beaches on Earth.", ageGroup: "teens" },
    { type: "tip", content: "Stay curious! Asking 'why' helps you understand the world much better.", ageGroup: "teens" },
    { type: "tip", content: "A balanced diet and regular exercise are key to keeping your energy levels high.", ageGroup: "teens" },
    { type: "tip", content: "Practicing mindfulness or meditation can help reduce stress during exam season.", ageGroup: "teens" },
    { type: "reading", content: "The Voyager 1 spacecraft is the most distant human-made object from Earth, currently traveling through interstellar space.", ageGroup: "teens" },
    { type: "reading", content: "The Mars Rover 'Curiosity' is about the size of a car and has been exploring the Martian surface since 2012.", ageGroup: "teens" },
    { type: "fact", content: "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.", ageGroup: "teens" },
    { type: "fact", content: "If two pieces of the same type of metal touch in space, they will permanently bond together. This is called cold welding.", ageGroup: "teens" },
    { type: "fact", content: "Uranus is the only planet in our solar system that rotates on its side.", ageGroup: "teens" },
    { type: "tip", content: "Volunteering for a cause you care about is a great way to gain experience and help others.", ageGroup: "teens" },
    { type: "tip", content: "Always check the sources of information you find online to avoid 'fake news'.", ageGroup: "teens" },

    // ADULTS
    { type: "quote", content: "Patience is not the ability to wait, but the ability to stay positive while waiting.", ageGroup: "adults" },
    { type: "info", content: "Aadhaar update can now be done online for some fields. Visit the official portal for details on correcting your address or date of birth.", ageGroup: "adults" },
    { type: "tip", content: "To reduce eye strain when working, follow the 20-20-20 rule: every 20 minutes, look at something 20 feet away for at least 20 seconds.", ageGroup: "adults" },
    { type: "poetry", content: "Two roads diverged in a wood, and I— I took the one less traveled by, And that has made all the difference. — Robert Frost", ageGroup: "adults" },
    { type: "info", content: "Most government offices are now moving towards paperless systems. Always check if you can submit documents digitally first.", ageGroup: "adults" },
    { type: "tip", content: "Drinking a glass of water right after waking up helps jumpstart your metabolism.", ageGroup: "adults" },
    { type: "fact", content: "The shortest war in history lasted only 38 minutes between Britain and Zanzibar in 1896.", ageGroup: "adults" },
    { type: "quote", content: "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt", ageGroup: "adults" },
    { type: "tip", content: "Cooking at home can save you thousands of dollars a year and is generally much healthier.", ageGroup: "adults" },
    { type: "info", content: "Did you know that you can track your public grievances online through the official portal?", ageGroup: "adults" },
    { type: "quote", content: "Do not wait for the perfect time and place to enter, for you are already onstage. — Unknown", ageGroup: "adults" },
    { type: "fact", content: "The average human spends about five years of their life waiting in lines and traffic.", ageGroup: "adults" },
    { type: "tip", content: "Stretching for just five minutes every hour can reduce body stiffness and improve circulation.", ageGroup: "adults" },
    { type: "reading", content: "Digital identity systems are helping governments deliver services faster and more efficiently.", ageGroup: "adults" },
    { type: "info", content: "You can now access many government services online without visiting offices physically.", ageGroup: "adults" },
    { type: "fact", content: "Olympus Mons on Mars is the tallest shield volcano in the solar system, standing at 21 km high.", ageGroup: "adults" },
    { type: "fact", content: "A light-year is the distance that light travels in one year, which is about 9.46 trillion kilometers.", ageGroup: "adults" },
    { type: "fact", content: "The International Space Station (ISS) travels at a speed of about 28,000 km/h, orbiting Earth every 90 minutes.", ageGroup: "adults" },
    { type: "fact", content: "There's a planet called 55 Cancri e that is thought to be covered in diamonds.", ageGroup: "adults" },
    { type: "fact", content: "The 'Boötes Void' is an enormous, nearly empty region of space, about 250 million light-years in diameter.", ageGroup: "adults" },
    { type: "tip", content: "Financial planning in your 20s and 30s can lead to a much more comfortable retirement.", ageGroup: "adults" },
    { type: "tip", content: "Maintaining a strong social network is linked to better mental health and a longer life.", ageGroup: "adults" },
    { type: "tip", content: "Regular dental checkups are crucial not just for your teeth, but for your overall health.", ageGroup: "adults" },
    { type: "reading", content: "The Hubble Space Telescope has provided some of the most detailed images of distant galaxies and nebulae ever captured.", ageGroup: "adults" },
    { type: "reading", content: "Commercial space travel is becoming a reality, with several private companies now offering flights to the edge of space.", ageGroup: "adults" },
    { type: "fact", content: "The Milky Way galaxy is expected to collide with the Andromeda galaxy in about 4.5 billion years.", ageGroup: "adults" },
    { type: "fact", content: "Cosmic microwave background radiation is the afterglow of the Big Bang, filling the entire universe.", ageGroup: "adults" },
    { type: "fact", content: "Quasars are the brightest objects in the universe, powered by supermassive black holes.", ageGroup: "adults" },
    { type: "tip", content: "Setting boundaries between your work and personal life is essential for preventing burnout.", ageGroup: "adults" },
    { type: "tip", content: "Learning a new skill or hobby keeps your brain sharp and improves your self-confidence.", ageGroup: "adults" },

    // SENIORS
    { type: "tip", content: "Stay active: A simple 15-minute walk daily can significantly improve your heart health and mood.", ageGroup: "seniors" },
    { type: "fact", content: "The world's oldest known tree is a Great Basin bristlecone pine located in California, estimated to be over 4,800 years old!", ageGroup: "seniors" },
    { type: "quote", content: "You are never too old to set another goal or to dream a new dream. — C.S. Lewis", ageGroup: "seniors" },
    { type: "reading", content: "Meditation and puzzles like Sudoku or crosswords are excellent ways to maintain cognitive health as we age.", ageGroup: "seniors" },
    { type: "tip", content: "Regular social interaction is as important for your health as a good diet.", ageGroup: "seniors" },
    { type: "fact", content: "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of the iron.", ageGroup: "seniors" },
    { type: "quote", content: "Life is what happens when you're busy making other plans. — John Lennon", ageGroup: "seniors" },
    { type: "tip", content: "Keep a small notepad by your bed to jot down things you don't want to forget in the morning.", ageGroup: "seniors" },
    { type: "reading", content: "Drinking green tea is linked to improved brain function and fat loss, among other impressive benefits.", ageGroup: "seniors" },
    { type: "fact", content: "A cloud can weigh as much as a million pounds.", ageGroup: "seniors" },
    { type: "quote", content: "Count your age by friends, not years. Count your life by smiles, not tears. — John Lennon", ageGroup: "seniors" },
    { type: "fact", content: "Walking regularly can reduce the risk of heart disease by up to 30 percent.", ageGroup: "seniors" },
    { type: "tip", content: "Drinking warm water in the morning can improve digestion.", ageGroup: "seniors" },
    { type: "reading", content: "Listening to music from your youth can help stimulate memory and improve mood.", ageGroup: "seniors" },
    { type: "fact", content: "Laughter boosts the immune system and helps relieve stress.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 2.47: 'Karmanye vadhikaraste ma phaleshu kadachana' - You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 6.5: 'Uddhared atmanatmanam natmanam avasadayet' - Elevate yourself through the power of your mind, and do not degrade yourself.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 4.7: 'Yada yada hi dharmasya glanir bhavati bharata' - Whenever there is a decline in righteousness, O Bharat, I manifest myself.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 2.22: 'Vasamsi jirnani yatha vihaya' - Just as a person puts on new garments, giving up old ones, the soul similarly accepts new bodies, giving up the old ones.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 18.66: 'Sarva-dharman parityajya mam ekam saranam vraja' - Abandon all varieties of religion and just surrender unto Me.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 2.63: 'Krodhad bhavati sammohah sammohat smriti-vibhramah' - From anger comes delusion; from delusion, loss of memory; from loss of memory, the destruction of discrimination.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 2.70: 'Apuryamanam achala-pratishtham' - One who remains undisturbed despite the flow of desires achieves peace.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 2.13: 'Dehino smin yatha dehe kaumaram yauvanam jara' - As the embodied soul continuously passes, in this body, from boyhood to youth to old age, the soul similarly passes into another body at death.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 5.18: 'Vidya-vinaya-sampanne brahmane gavi hastini' - The humble sages, by virtue of true knowledge, see with equal vision a learned Brahmin, a cow, an elephant, a dog, and a dog-eater.", ageGroup: "seniors" },
    { type: "reading", content: "Bhagavad Gita 10.41: 'Yad yad vibhutimat sattvam srimad urjitam eva va' - Know that all opulent, beautiful and glorious creations spring from but a spark of My splendor.", ageGroup: "seniors" },
    { type: "fact", content: "The James Webb Space Telescope is the most powerful telescope ever built, designed to look back at the very first stars and galaxies.", ageGroup: "seniors" },
    { type: "fact", content: "The planet Saturn has 146 moons, the most of any planet in our solar system.", ageGroup: "seniors" },
    { type: "fact", content: "Earth is the only known planet to have liquid water on its surface.", ageGroup: "seniors" },
    { type: "tip", content: "Spending time with grandchildren can provide a sense of purpose and joy, and it's good for their development too!", ageGroup: "seniors" },
    { type: "tip", content: "Keeping your mind active with crosswords or reading helps maintain mental clarity.", ageGroup: "seniors" }
];

async function seed() {
    try {
        await mongoose.connect(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/queuepro');

        console.log("Connected to MongoDB");

        await Puzzle.deleteMany({});
        await EngagementContent.deleteMany({});
        console.log("Cleared existing engagement data.");

        await Puzzle.insertMany(puzzles);
        await EngagementContent.insertMany(contentItems);

        console.log(`Successfully seeded ${puzzles.length} puzzles and ${contentItems.length} content items.`);

        process.exit(0);
    } catch (err) {
        console.error("Error seeding data:", err);
        process.exit(1);
    }
}

seed();
